configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/meorphis-test%2Fmeorphis-test-74a52b29d09d567daa7bf55d4678d3cf175449a02560484fa3450e2044d1c3e4.yml
