// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import type { RequestInit, RequestInfo, BodyInit } from './internal/builtin-types';
import type { HTTPMethod, PromiseOrValue, MergedRequestInit, FinalizedRequestInit } from './internal/types';
import { uuid4 } from './internal/utils/uuid';
import { validatePositiveInteger, isAbsoluteURL, safeJSON } from './internal/utils/values';
import { sleep } from './internal/utils/sleep';
export type { Logger, LogLevel } from './internal/utils/log';
import { castToError, isAbortError } from './internal/errors';
import type { APIResponseProps } from './internal/parse';
import { getPlatformHeaders } from './internal/detect-platform';
import * as Shims from './internal/shims';
import * as Opts from './internal/request-options';
import { stringifyQuery } from './internal/utils/query';
import { VERSION } from './version';
import * as Errors from './core/error';
import * as Uploads from './core/uploads';
import * as API from './resources/index';
import { APIPromise } from './core/api-promise';
import {
  ActionListParams,
  ActionListResponse,
  ActionListV2Params,
  ActionListV2Response,
  ActionRetrieveResponse,
  ActionRetrieveV2Response,
  ActionV1,
  ActionV2,
  Actions,
  ActorV2,
  AlertActorV2,
  UserV1,
  UserV2,
  WorkflowActorV2,
} from './resources/actions';
import {
  AlertAttributeCreateParams,
  AlertAttributeCreateResponse,
  AlertAttributeListResponse,
  AlertAttributeRetrieveResponse,
  AlertAttributeUpdateParams,
  AlertAttributeUpdateResponse,
  AlertAttributeV2,
  AlertAttributes,
} from './resources/alert-attributes';
import {
  AlertEventCreateHTTPParams,
  AlertEventCreateHTTPResponse,
  AlertEvents,
} from './resources/alert-events';
import {
  AlertRoute,
  AlertRouteCreateParams,
  AlertRouteCreateResponse,
  AlertRouteListParams,
  AlertRouteListResponse,
  AlertRouteRetrieveResponse,
  AlertRouteUpdateParams,
  AlertRouteUpdateResponse,
  AlertRoutes,
  AlertSourcePayload,
  AutoGeneratedTemplateBinding,
  AutoGeneratedTemplateBindingPayload,
  ChannelConfigPayload,
  ChannelTarget,
  ChannelTargetPayload,
  ConditionGroup,
  ConditionGroupPayload,
  EscalationConfigPayload,
  Expression,
  ExpressionPayload,
  GroupingKey,
  IncidentConfigPayload,
  IncidentTemplatePayload,
  PaginationMetaResult,
  ReturnsMeta,
  TemplateBinding,
  TemplateBindingPayload,
} from './resources/alert-routes';
import {
  AlertSource,
  AlertSourceCreateParams,
  AlertSourceCreateResponse,
  AlertSourceListResponse,
  AlertSourceRetrieveResponse,
  AlertSourceUpdateParams,
  AlertSourceUpdateResponse,
  AlertSources,
  HTTPCustomOptions,
  JiraOptions,
  ParamBindingValue,
  ParamBindingValuePayload,
  TemplatePayload,
} from './resources/alert-sources';
import {
  AlertAttributeValueV2,
  AlertListParams,
  AlertListResponse,
  AlertRetrieveResponse,
  AlertV2,
  Alerts,
} from './resources/alerts';
import {
  CatalogEntries,
  CatalogEntryCreateEntryV2Params,
  CatalogEntryCreateEntryV2Response,
  CatalogEntryCreateEntryV3Params,
  CatalogEntryCreateEntryV3Response,
  CatalogEntryListEntriesV2Params,
  CatalogEntryListEntriesV2Response,
  CatalogEntryListEntriesV3Params,
  CatalogEntryListEntriesV3Response,
  CatalogEntryShowEntryV2Response,
  CatalogEntryShowEntryV3Response,
  CatalogEntryUpdateEntryV2Params,
  CatalogEntryUpdateEntryV2Response,
  CatalogEntryUpdateEntryV3Params,
  CatalogEntryUpdateEntryV3Response,
  CatalogEntryV2,
  CatalogEntryV3,
  CatalogTypeV2,
  CatalogTypeV3,
} from './resources/catalog-entries';
import {
  CatalogResourceListV2Response,
  CatalogResourceListV3Response,
  CatalogResources,
} from './resources/catalog-resources';
import {
  CustomFieldOptionCreateParams,
  CustomFieldOptionCreateResponse,
  CustomFieldOptionListParams,
  CustomFieldOptionListResponse,
  CustomFieldOptionRetrieveResponse,
  CustomFieldOptionUpdateParams,
  CustomFieldOptionUpdateResponse,
  CustomFieldOptionV1,
  CustomFieldOptions,
  PaginationMeta,
} from './resources/custom-field-options';
import {
  CustomFieldCreateV1Params,
  CustomFieldCreateV1Response,
  CustomFieldCreateV2Params,
  CustomFieldCreateV2Response,
  CustomFieldFilterByOptionsV2,
  CustomFieldListV1Response,
  CustomFieldListV2Response,
  CustomFieldRetrieveV1Response,
  CustomFieldRetrieveV2Response,
  CustomFieldUpdateV1Params,
  CustomFieldUpdateV1Response,
  CustomFieldUpdateV2Params,
  CustomFieldUpdateV2Response,
  CustomFieldV1,
  CustomFieldV2,
  CustomFields,
} from './resources/custom-fields';
import {
  EscalationPath,
  EscalationPathCreateParams,
  EscalationPathCreateResponse,
  EscalationPathNode,
  EscalationPathNodeIfElse,
  EscalationPathNodeIfElsePayload,
  EscalationPathNodePayload,
  EscalationPathRetrieveResponse,
  EscalationPathUpdateParams,
  EscalationPathUpdateResponse,
  EscalationPaths,
  WeekdayIntervalConfig,
} from './resources/escalation-paths';
import {
  EscalationCreateParams,
  EscalationCreateResponse,
  EscalationListParams,
  EscalationListResponse,
  EscalationRetrieveResponse,
  EscalationV2,
  Escalations,
} from './resources/escalations';
import {
  ExternalIssueReference,
  FollowUp,
  FollowUpListParams,
  FollowUpListResponse,
  FollowUpRetrieveResponse,
  FollowUps,
} from './resources/follow-ups';
import { Identity, IdentityRetrieveResponse } from './resources/identity';
import {
  AlertSlim,
  IncidentAlertListParams,
  IncidentAlertListResponse,
  IncidentAlerts,
  IncidentSlim,
} from './resources/incident-alerts';
import {
  IncidentAttachment,
  IncidentAttachmentCreateParams,
  IncidentAttachmentCreateResponse,
  IncidentAttachmentListParams,
  IncidentAttachmentListResponse,
  IncidentAttachments,
} from './resources/incident-attachments';
import {
  IncidentRelationshipListParams,
  IncidentRelationshipListResponse,
  IncidentRelationships,
} from './resources/incident-relationships';
import {
  IncidentRoleCreateParams,
  IncidentRoleCreateResponse,
  IncidentRoleCreateV2Params,
  IncidentRoleCreateV2Response,
  IncidentRoleListResponse,
  IncidentRoleListV2Response,
  IncidentRoleRetrieveResponse,
  IncidentRoleRetrieveV2Response,
  IncidentRoleUpdateParams,
  IncidentRoleUpdateResponse,
  IncidentRoleUpdateV2Params,
  IncidentRoleUpdateV2Response,
  IncidentRoleV1,
  IncidentRoleV2,
  IncidentRoles,
} from './resources/incident-roles';
import {
  IncidentStatusCreateParams,
  IncidentStatusCreateResponse,
  IncidentStatusListResponse,
  IncidentStatusRetrieveResponse,
  IncidentStatusUpdateParams,
  IncidentStatusUpdateResponse,
  IncidentStatusV1,
  IncidentStatuses,
} from './resources/incident-statuses';
import {
  IncidentTimestamp,
  IncidentTimestampListResponse,
  IncidentTimestampRetrieveResponse,
  IncidentTimestamps,
} from './resources/incident-timestamps';
import {
  IncidentType,
  IncidentTypeListResponse,
  IncidentTypeRetrieveResponse,
  IncidentTypes,
} from './resources/incident-types';
import {
  IncidentUpdateListParams,
  IncidentUpdateListResponse,
  IncidentUpdates,
} from './resources/incident-updates';
import {
  IPAllowlist,
  IPAllowlistItem,
  IPAllowlistRetrieveResponse,
  IPAllowlistUpdateParams,
  IPAllowlistUpdateResponse,
  IPAllowlists,
} from './resources/ip-allowlists';
import { OpenAPIJson, OpenAPIJsonRetrieveResponse } from './resources/openapi-json';
import { OpenAPIV3Json, OpenAPIV3JsonRetrieveResponse } from './resources/openapi-v3-json';
import {
  ScheduleEntries,
  ScheduleEntry,
  ScheduleEntryListParams,
  ScheduleEntryListResponse,
} from './resources/schedule-entries';
import {
  ScheduleOverrideCreateParams,
  ScheduleOverrideCreateResponse,
  ScheduleOverrides,
  UserReferencePayloadV2,
} from './resources/schedule-overrides';
import {
  Schedule,
  ScheduleCreateParams,
  ScheduleCreateResponse,
  ScheduleHolidaysPublicConfigPayload,
  ScheduleListParams,
  ScheduleListResponse,
  ScheduleRetrieveResponse,
  ScheduleRotationHandover,
  ScheduleRotationWorkingInterval,
  ScheduleUpdateParams,
  ScheduleUpdateResponse,
  Schedules,
} from './resources/schedules';
import {
  Severities,
  SeverityCreateParams,
  SeverityCreateResponse,
  SeverityListResponse,
  SeverityRetrieveResponse,
  SeverityUpdateParams,
  SeverityUpdateResponse,
  SeverityV1,
} from './resources/severities';
import {
  RbacRole,
  UserListParams,
  UserListResponse,
  UserRetrieveResponse,
  UserWithRoles,
  Users,
} from './resources/users';
import {
  EngineParamBinding,
  EngineParamBindingPayload,
  EngineReference,
  ManagementMeta,
  StepConfigPayload,
  TriggerSlim,
  Workflow,
  WorkflowCreateParams,
  WorkflowCreateResponse,
  WorkflowDelay,
  WorkflowListResponse,
  WorkflowRetrieveParams,
  WorkflowRetrieveResponse,
  WorkflowUpdateParams,
  WorkflowUpdateResponse,
  Workflows,
} from './resources/workflows';
import {
  CatalogTypeCreateParams,
  CatalogTypeCreateResponse,
  CatalogTypeListResponse,
  CatalogTypeRetrieveResponse,
  CatalogTypeUpdateParams,
  CatalogTypeUpdateResponse,
  CatalogTypes,
} from './resources/catalog-types/catalog-types';
import {
  IncidentMembershipCreateParams,
  IncidentMembershipCreateResponse,
  IncidentMemberships,
} from './resources/incident-memberships/incident-memberships';
import {
  CustomFieldEntryPayload,
  CustomFieldOptionV2,
  IncidentCreateParams,
  IncidentCreateResponse,
  IncidentCreateV2Params,
  IncidentCreateV2Response,
  IncidentListParams,
  IncidentListResponse,
  IncidentListV2Params,
  IncidentListV2Response,
  IncidentRetrieveResponse,
  IncidentRetrieveV2Response,
  IncidentRoleAssignmentPayload,
  IncidentStatusV2,
  IncidentTimestampValuePayload,
  IncidentV1,
  IncidentV2,
  Incidents,
  PaginationMetaResultWithTotal,
  Severity,
} from './resources/incidents/incidents';
import { StatusPages } from './resources/status-pages/status-pages';
import { type Fetch } from './internal/builtin-types';
import { HeadersLike, NullableHeaders, buildHeaders } from './internal/headers';
import { FinalRequestOptions, RequestOptions } from './internal/request-options';
import { readEnv } from './internal/utils/env';
import {
  type LogLevel,
  type Logger,
  formatRequestDetails,
  loggerFor,
  parseLogLevel,
} from './internal/utils/log';
import { isEmptyObj } from './internal/utils/values';

export interface ClientOptions {
  /**
   * Defaults to process.env['INCIDENT_IO_2_API_KEY'].
   */
  apiKey?: string | null | undefined;

  /**
   * Override the default base URL for the API, e.g., "https://api.example.com/v2/"
   *
   * Defaults to process.env['INCIDENT_IO_6_BASE_URL'].
   */
  baseURL?: string | null | undefined;

  /**
   * The maximum amount of time (in milliseconds) that the client should wait for a response
   * from the server before timing out a single request.
   *
   * Note that request timeouts are retried by default, so in a worst-case scenario you may wait
   * much longer than this timeout before the promise succeeds or fails.
   *
   * @unit milliseconds
   */
  timeout?: number | undefined;
  /**
   * Additional `RequestInit` options to be passed to `fetch` calls.
   * Properties will be overridden by per-request `fetchOptions`.
   */
  fetchOptions?: MergedRequestInit | undefined;

  /**
   * Specify a custom `fetch` function implementation.
   *
   * If not provided, we expect that `fetch` is defined globally.
   */
  fetch?: Fetch | undefined;

  /**
   * The maximum number of times that the client will retry a request in case of a
   * temporary failure, like a network error or a 5XX error from the server.
   *
   * @default 2
   */
  maxRetries?: number | undefined;

  /**
   * Default headers to include with every request to the API.
   *
   * These can be removed in individual requests by explicitly setting the
   * header to `null` in request options.
   */
  defaultHeaders?: HeadersLike | undefined;

  /**
   * Default query parameters to include with every request to the API.
   *
   * These can be removed in individual requests by explicitly setting the
   * param to `undefined` in request options.
   */
  defaultQuery?: Record<string, string | undefined> | undefined;

  /**
   * Set the log level.
   *
   * Defaults to process.env['INCIDENT_IO_6_LOG'] or 'warn' if it isn't set.
   */
  logLevel?: LogLevel | undefined;

  /**
   * Set the logger.
   *
   * Defaults to globalThis.console.
   */
  logger?: Logger | undefined;
}

/**
 * API Client for interfacing with the Incident Io 6 API.
 */
export class IncidentIo6 {
  apiKey: string | null;

  baseURL: string;
  maxRetries: number;
  timeout: number;
  logger: Logger;
  logLevel: LogLevel | undefined;
  fetchOptions: MergedRequestInit | undefined;

  private fetch: Fetch;
  #encoder: Opts.RequestEncoder;
  protected idempotencyHeader?: string;
  private _options: ClientOptions;

  /**
   * API Client for interfacing with the Incident Io 6 API.
   *
   * @param {string | null | undefined} [opts.apiKey=process.env['INCIDENT_IO_2_API_KEY'] ?? null]
   * @param {string} [opts.baseURL=process.env['INCIDENT_IO_6_BASE_URL'] ?? https://api.incident.io] - Override the default base URL for the API.
   * @param {number} [opts.timeout=1 minute] - The maximum amount of time (in milliseconds) the client will wait for a response before timing out.
   * @param {MergedRequestInit} [opts.fetchOptions] - Additional `RequestInit` options to be passed to `fetch` calls.
   * @param {Fetch} [opts.fetch] - Specify a custom `fetch` function implementation.
   * @param {number} [opts.maxRetries=2] - The maximum number of times the client will retry a request.
   * @param {HeadersLike} opts.defaultHeaders - Default headers to include with every request to the API.
   * @param {Record<string, string | undefined>} opts.defaultQuery - Default query parameters to include with every request to the API.
   */
  constructor({
    baseURL = readEnv('INCIDENT_IO_6_BASE_URL'),
    apiKey = readEnv('INCIDENT_IO_2_API_KEY') ?? null,
    ...opts
  }: ClientOptions = {}) {
    const options: ClientOptions = {
      apiKey,
      ...opts,
      baseURL: baseURL || `https://api.incident.io`,
    };

    this.baseURL = options.baseURL!;
    this.timeout = options.timeout ?? IncidentIo6.DEFAULT_TIMEOUT /* 1 minute */;
    this.logger = options.logger ?? console;
    const defaultLogLevel = 'warn';
    // Set default logLevel early so that we can log a warning in parseLogLevel.
    this.logLevel = defaultLogLevel;
    this.logLevel =
      parseLogLevel(options.logLevel, 'ClientOptions.logLevel', this) ??
      parseLogLevel(readEnv('INCIDENT_IO_6_LOG'), "process.env['INCIDENT_IO_6_LOG']", this) ??
      defaultLogLevel;
    this.fetchOptions = options.fetchOptions;
    this.maxRetries = options.maxRetries ?? 2;
    this.fetch = options.fetch ?? Shims.getDefaultFetch();
    this.#encoder = Opts.FallbackEncoder;

    this._options = options;

    this.apiKey = apiKey;
  }

  /**
   * Create a new client instance re-using the same options given to the current client with optional overriding.
   */
  withOptions(options: Partial<ClientOptions>): this {
    const client = new (this.constructor as any as new (props: ClientOptions) => typeof this)({
      ...this._options,
      baseURL: this.baseURL,
      maxRetries: this.maxRetries,
      timeout: this.timeout,
      logger: this.logger,
      logLevel: this.logLevel,
      fetch: this.fetch,
      fetchOptions: this.fetchOptions,
      apiKey: this.apiKey,
      ...options,
    });
    return client;
  }

  /**
   * Check whether the base URL is set to its default.
   */
  #baseURLOverridden(): boolean {
    return this.baseURL !== 'https://api.incident.io';
  }

  protected defaultQuery(): Record<string, string | undefined> | undefined {
    return this._options.defaultQuery;
  }

  protected validateHeaders({ values, nulls }: NullableHeaders) {
    if (this.apiKey && values.get('authorization')) {
      return;
    }
    if (nulls.has('authorization')) {
      return;
    }

    throw new Error(
      'Could not resolve authentication method. Expected the apiKey to be set. Or for the "Authorization" headers to be explicitly omitted',
    );
  }

  protected async authHeaders(opts: FinalRequestOptions): Promise<NullableHeaders | undefined> {
    if (this.apiKey == null) {
      return undefined;
    }
    return buildHeaders([{ Authorization: `Bearer ${this.apiKey}` }]);
  }

  protected stringifyQuery(query: object | Record<string, unknown>): string {
    return stringifyQuery(query);
  }

  private getUserAgent(): string {
    return `${this.constructor.name}/JS ${VERSION}`;
  }

  protected defaultIdempotencyKey(): string {
    return `stainless-node-retry-${uuid4()}`;
  }

  protected makeStatusError(
    status: number,
    error: Object,
    message: string | undefined,
    headers: Headers,
  ): Errors.APIError {
    return Errors.APIError.generate(status, error, message, headers);
  }

  buildURL(
    path: string,
    query: Record<string, unknown> | null | undefined,
    defaultBaseURL?: string | undefined,
  ): string {
    const baseURL = (!this.#baseURLOverridden() && defaultBaseURL) || this.baseURL;
    const url =
      isAbsoluteURL(path) ?
        new URL(path)
      : new URL(baseURL + (baseURL.endsWith('/') && path.startsWith('/') ? path.slice(1) : path));

    const defaultQuery = this.defaultQuery();
    const pathQuery = Object.fromEntries(url.searchParams);
    if (!isEmptyObj(defaultQuery) || !isEmptyObj(pathQuery)) {
      query = { ...pathQuery, ...defaultQuery, ...query };
    }

    if (typeof query === 'object' && query && !Array.isArray(query)) {
      url.search = this.stringifyQuery(query);
    }

    return url.toString();
  }

  /**
   * Used as a callback for mutating the given `FinalRequestOptions` object.
   */
  protected async prepareOptions(options: FinalRequestOptions): Promise<void> {}

  /**
   * Used as a callback for mutating the given `RequestInit` object.
   *
   * This is useful for cases where you want to add certain headers based off of
   * the request properties, e.g. `method` or `url`.
   */
  protected async prepareRequest(
    request: RequestInit,
    { url, options }: { url: string; options: FinalRequestOptions },
  ): Promise<void> {}

  get<Rsp>(path: string, opts?: PromiseOrValue<RequestOptions>): APIPromise<Rsp> {
    return this.methodRequest('get', path, opts);
  }

  post<Rsp>(path: string, opts?: PromiseOrValue<RequestOptions>): APIPromise<Rsp> {
    return this.methodRequest('post', path, opts);
  }

  patch<Rsp>(path: string, opts?: PromiseOrValue<RequestOptions>): APIPromise<Rsp> {
    return this.methodRequest('patch', path, opts);
  }

  put<Rsp>(path: string, opts?: PromiseOrValue<RequestOptions>): APIPromise<Rsp> {
    return this.methodRequest('put', path, opts);
  }

  delete<Rsp>(path: string, opts?: PromiseOrValue<RequestOptions>): APIPromise<Rsp> {
    return this.methodRequest('delete', path, opts);
  }

  private methodRequest<Rsp>(
    method: HTTPMethod,
    path: string,
    opts?: PromiseOrValue<RequestOptions>,
  ): APIPromise<Rsp> {
    return this.request(
      Promise.resolve(opts).then((opts) => {
        return { method, path, ...opts };
      }),
    );
  }

  request<Rsp>(
    options: PromiseOrValue<FinalRequestOptions>,
    remainingRetries: number | null = null,
  ): APIPromise<Rsp> {
    return new APIPromise(this, this.makeRequest(options, remainingRetries, undefined));
  }

  private async makeRequest(
    optionsInput: PromiseOrValue<FinalRequestOptions>,
    retriesRemaining: number | null,
    retryOfRequestLogID: string | undefined,
  ): Promise<APIResponseProps> {
    const options = await optionsInput;
    const maxRetries = options.maxRetries ?? this.maxRetries;
    if (retriesRemaining == null) {
      retriesRemaining = maxRetries;
    }

    await this.prepareOptions(options);

    const { req, url, timeout } = await this.buildRequest(options, {
      retryCount: maxRetries - retriesRemaining,
    });

    await this.prepareRequest(req, { url, options });

    /** Not an API request ID, just for correlating local log entries. */
    const requestLogID = 'log_' + ((Math.random() * (1 << 24)) | 0).toString(16).padStart(6, '0');
    const retryLogStr = retryOfRequestLogID === undefined ? '' : `, retryOf: ${retryOfRequestLogID}`;
    const startTime = Date.now();

    loggerFor(this).debug(
      `[${requestLogID}] sending request`,
      formatRequestDetails({
        retryOfRequestLogID,
        method: options.method,
        url,
        options,
        headers: req.headers,
      }),
    );

    if (options.signal?.aborted) {
      throw new Errors.APIUserAbortError();
    }

    const controller = new AbortController();
    const response = await this.fetchWithTimeout(url, req, timeout, controller).catch(castToError);
    const headersTime = Date.now();

    if (response instanceof globalThis.Error) {
      const retryMessage = `retrying, ${retriesRemaining} attempts remaining`;
      if (options.signal?.aborted) {
        throw new Errors.APIUserAbortError();
      }
      // detect native connection timeout errors
      // deno throws "TypeError: error sending request for url (https://example/): client error (Connect): tcp connect error: Operation timed out (os error 60): Operation timed out (os error 60)"
      // undici throws "TypeError: fetch failed" with cause "ConnectTimeoutError: Connect Timeout Error (attempted address: example:443, timeout: 1ms)"
      // others do not provide enough information to distinguish timeouts from other connection errors
      const isTimeout =
        isAbortError(response) ||
        /timed? ?out/i.test(String(response) + ('cause' in response ? String(response.cause) : ''));
      if (retriesRemaining) {
        loggerFor(this).info(
          `[${requestLogID}] connection ${isTimeout ? 'timed out' : 'failed'} - ${retryMessage}`,
        );
        loggerFor(this).debug(
          `[${requestLogID}] connection ${isTimeout ? 'timed out' : 'failed'} (${retryMessage})`,
          formatRequestDetails({
            retryOfRequestLogID,
            url,
            durationMs: headersTime - startTime,
            message: response.message,
          }),
        );
        return this.retryRequest(options, retriesRemaining, retryOfRequestLogID ?? requestLogID);
      }
      loggerFor(this).info(
        `[${requestLogID}] connection ${isTimeout ? 'timed out' : 'failed'} - error; no more retries left`,
      );
      loggerFor(this).debug(
        `[${requestLogID}] connection ${isTimeout ? 'timed out' : 'failed'} (error; no more retries left)`,
        formatRequestDetails({
          retryOfRequestLogID,
          url,
          durationMs: headersTime - startTime,
          message: response.message,
        }),
      );
      if (isTimeout) {
        throw new Errors.APIConnectionTimeoutError();
      }
      throw new Errors.APIConnectionError({ cause: response });
    }

    const responseInfo = `[${requestLogID}${retryLogStr}] ${req.method} ${url} ${
      response.ok ? 'succeeded' : 'failed'
    } with status ${response.status} in ${headersTime - startTime}ms`;

    if (!response.ok) {
      const shouldRetry = await this.shouldRetry(response);
      if (retriesRemaining && shouldRetry) {
        const retryMessage = `retrying, ${retriesRemaining} attempts remaining`;

        // We don't need the body of this response.
        await Shims.CancelReadableStream(response.body);
        loggerFor(this).info(`${responseInfo} - ${retryMessage}`);
        loggerFor(this).debug(
          `[${requestLogID}] response error (${retryMessage})`,
          formatRequestDetails({
            retryOfRequestLogID,
            url: response.url,
            status: response.status,
            headers: response.headers,
            durationMs: headersTime - startTime,
          }),
        );
        return this.retryRequest(
          options,
          retriesRemaining,
          retryOfRequestLogID ?? requestLogID,
          response.headers,
        );
      }

      const retryMessage = shouldRetry ? `error; no more retries left` : `error; not retryable`;

      loggerFor(this).info(`${responseInfo} - ${retryMessage}`);

      const errText = await response.text().catch((err: any) => castToError(err).message);
      const errJSON = safeJSON(errText) as any;
      const errMessage = errJSON ? undefined : errText;

      loggerFor(this).debug(
        `[${requestLogID}] response error (${retryMessage})`,
        formatRequestDetails({
          retryOfRequestLogID,
          url: response.url,
          status: response.status,
          headers: response.headers,
          message: errMessage,
          durationMs: Date.now() - startTime,
        }),
      );

      const err = this.makeStatusError(response.status, errJSON, errMessage, response.headers);
      throw err;
    }

    loggerFor(this).info(responseInfo);
    loggerFor(this).debug(
      `[${requestLogID}] response start`,
      formatRequestDetails({
        retryOfRequestLogID,
        url: response.url,
        status: response.status,
        headers: response.headers,
        durationMs: headersTime - startTime,
      }),
    );

    return { response, options, controller, requestLogID, retryOfRequestLogID, startTime };
  }

  async fetchWithTimeout(
    url: RequestInfo,
    init: RequestInit | undefined,
    ms: number,
    controller: AbortController,
  ): Promise<Response> {
    const { signal, method, ...options } = init || {};
    const abort = this._makeAbort(controller);
    if (signal) signal.addEventListener('abort', abort, { once: true });

    const timeout = setTimeout(abort, ms);

    const isReadableBody =
      ((globalThis as any).ReadableStream && options.body instanceof (globalThis as any).ReadableStream) ||
      (typeof options.body === 'object' && options.body !== null && Symbol.asyncIterator in options.body);

    const fetchOptions: RequestInit = {
      signal: controller.signal as any,
      ...(isReadableBody ? { duplex: 'half' } : {}),
      method: 'GET',
      ...options,
    };
    if (method) {
      // Custom methods like 'patch' need to be uppercased
      // See https://github.com/nodejs/undici/issues/2294
      fetchOptions.method = method.toUpperCase();
    }

    try {
      // use undefined this binding; fetch errors if bound to something else in browser/cloudflare
      return await this.fetch.call(undefined, url, fetchOptions);
    } finally {
      clearTimeout(timeout);
    }
  }

  private async shouldRetry(response: Response): Promise<boolean> {
    // Note this is not a standard header.
    const shouldRetryHeader = response.headers.get('x-should-retry');

    // If the server explicitly says whether or not to retry, obey.
    if (shouldRetryHeader === 'true') return true;
    if (shouldRetryHeader === 'false') return false;

    // Retry on request timeouts.
    if (response.status === 408) return true;

    // Retry on lock timeouts.
    if (response.status === 409) return true;

    // Retry on rate limits.
    if (response.status === 429) return true;

    // Retry internal errors.
    if (response.status >= 500) return true;

    return false;
  }

  private async retryRequest(
    options: FinalRequestOptions,
    retriesRemaining: number,
    requestLogID: string,
    responseHeaders?: Headers | undefined,
  ): Promise<APIResponseProps> {
    let timeoutMillis: number | undefined;

    // Note the `retry-after-ms` header may not be standard, but is a good idea and we'd like proactive support for it.
    const retryAfterMillisHeader = responseHeaders?.get('retry-after-ms');
    if (retryAfterMillisHeader) {
      const timeoutMs = parseFloat(retryAfterMillisHeader);
      if (!Number.isNaN(timeoutMs)) {
        timeoutMillis = timeoutMs;
      }
    }

    // About the Retry-After header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After
    const retryAfterHeader = responseHeaders?.get('retry-after');
    if (retryAfterHeader && !timeoutMillis) {
      const timeoutSeconds = parseFloat(retryAfterHeader);
      if (!Number.isNaN(timeoutSeconds)) {
        timeoutMillis = timeoutSeconds * 1000;
      } else {
        timeoutMillis = Date.parse(retryAfterHeader) - Date.now();
      }
    }

    // If the API asks us to wait a certain amount of time, just do what it
    // says, but otherwise calculate a default
    if (timeoutMillis === undefined) {
      const maxRetries = options.maxRetries ?? this.maxRetries;
      timeoutMillis = this.calculateDefaultRetryTimeoutMillis(retriesRemaining, maxRetries);
    }
    await sleep(timeoutMillis);

    return this.makeRequest(options, retriesRemaining - 1, requestLogID);
  }

  private calculateDefaultRetryTimeoutMillis(retriesRemaining: number, maxRetries: number): number {
    const initialRetryDelay = 0.5;
    const maxRetryDelay = 8.0;

    const numRetries = maxRetries - retriesRemaining;

    // Apply exponential backoff, but not more than the max.
    const sleepSeconds = Math.min(initialRetryDelay * Math.pow(2, numRetries), maxRetryDelay);

    // Apply some jitter, take up to at most 25 percent of the retry time.
    const jitter = 1 - Math.random() * 0.25;

    return sleepSeconds * jitter * 1000;
  }

  async buildRequest(
    inputOptions: FinalRequestOptions,
    { retryCount = 0 }: { retryCount?: number } = {},
  ): Promise<{ req: FinalizedRequestInit; url: string; timeout: number }> {
    const options = { ...inputOptions };
    const { method, path, query, defaultBaseURL } = options;

    const url = this.buildURL(path!, query as Record<string, unknown>, defaultBaseURL);
    if ('timeout' in options) validatePositiveInteger('timeout', options.timeout);
    options.timeout = options.timeout ?? this.timeout;
    const { bodyHeaders, body } = this.buildBody({ options });
    const reqHeaders = await this.buildHeaders({ options: inputOptions, method, bodyHeaders, retryCount });

    const req: FinalizedRequestInit = {
      method,
      headers: reqHeaders,
      ...(options.signal && { signal: options.signal }),
      ...((globalThis as any).ReadableStream &&
        body instanceof (globalThis as any).ReadableStream && { duplex: 'half' }),
      ...(body && { body }),
      ...((this.fetchOptions as any) ?? {}),
      ...((options.fetchOptions as any) ?? {}),
    };

    return { req, url, timeout: options.timeout };
  }

  private async buildHeaders({
    options,
    method,
    bodyHeaders,
    retryCount,
  }: {
    options: FinalRequestOptions;
    method: HTTPMethod;
    bodyHeaders: HeadersLike;
    retryCount: number;
  }): Promise<Headers> {
    let idempotencyHeaders: HeadersLike = {};
    if (this.idempotencyHeader && method !== 'get') {
      if (!options.idempotencyKey) options.idempotencyKey = this.defaultIdempotencyKey();
      idempotencyHeaders[this.idempotencyHeader] = options.idempotencyKey;
    }

    const headers = buildHeaders([
      idempotencyHeaders,
      {
        Accept: 'application/json',
        'User-Agent': this.getUserAgent(),
        'X-Stainless-Retry-Count': String(retryCount),
        ...(options.timeout ? { 'X-Stainless-Timeout': String(Math.trunc(options.timeout / 1000)) } : {}),
        ...getPlatformHeaders(),
      },
      await this.authHeaders(options),
      this._options.defaultHeaders,
      bodyHeaders,
      options.headers,
    ]);

    this.validateHeaders(headers);

    return headers.values;
  }

  private _makeAbort(controller: AbortController) {
    // note: we can't just inline this method inside `fetchWithTimeout()` because then the closure
    //       would capture all request options, and cause a memory leak.
    return () => controller.abort();
  }

  private buildBody({ options: { body, headers: rawHeaders } }: { options: FinalRequestOptions }): {
    bodyHeaders: HeadersLike;
    body: BodyInit | undefined;
  } {
    if (!body) {
      return { bodyHeaders: undefined, body: undefined };
    }
    const headers = buildHeaders([rawHeaders]);
    if (
      // Pass raw type verbatim
      ArrayBuffer.isView(body) ||
      body instanceof ArrayBuffer ||
      body instanceof DataView ||
      (typeof body === 'string' &&
        // Preserve legacy string encoding behavior for now
        headers.values.has('content-type')) ||
      // `Blob` is superset of `File`
      ((globalThis as any).Blob && body instanceof (globalThis as any).Blob) ||
      // `FormData` -> `multipart/form-data`
      body instanceof FormData ||
      // `URLSearchParams` -> `application/x-www-form-urlencoded`
      body instanceof URLSearchParams ||
      // Send chunked stream (each chunk has own `length`)
      ((globalThis as any).ReadableStream && body instanceof (globalThis as any).ReadableStream)
    ) {
      return { bodyHeaders: undefined, body: body as BodyInit };
    } else if (
      typeof body === 'object' &&
      (Symbol.asyncIterator in body ||
        (Symbol.iterator in body && 'next' in body && typeof body.next === 'function'))
    ) {
      return { bodyHeaders: undefined, body: Shims.ReadableStreamFrom(body as AsyncIterable<Uint8Array>) };
    } else if (
      typeof body === 'object' &&
      headers.values.get('content-type') === 'application/x-www-form-urlencoded'
    ) {
      return {
        bodyHeaders: { 'content-type': 'application/x-www-form-urlencoded' },
        body: this.stringifyQuery(body),
      };
    } else {
      return this.#encoder({ body, headers });
    }
  }

  static IncidentIo6 = this;
  static DEFAULT_TIMEOUT = 60000; // 1 minute

  static IncidentIo6Error = Errors.IncidentIo6Error;
  static APIError = Errors.APIError;
  static APIConnectionError = Errors.APIConnectionError;
  static APIConnectionTimeoutError = Errors.APIConnectionTimeoutError;
  static APIUserAbortError = Errors.APIUserAbortError;
  static NotFoundError = Errors.NotFoundError;
  static ConflictError = Errors.ConflictError;
  static RateLimitError = Errors.RateLimitError;
  static BadRequestError = Errors.BadRequestError;
  static AuthenticationError = Errors.AuthenticationError;
  static InternalServerError = Errors.InternalServerError;
  static PermissionDeniedError = Errors.PermissionDeniedError;
  static UnprocessableEntityError = Errors.UnprocessableEntityError;

  static toFile = Uploads.toFile;

  actions: API.Actions = new API.Actions(this);
  /**
   * Manage custom field options.
   *
   * Single- and multi-select custom fields have a list of all available options,
   * which have a value, and a sort key. The value must be unique to the custom
   * field. For example, you might have an Incident Type custom field, with options
   * "Data breach", "Performance degradation", "API downtime", etc.
   */
  customFieldOptions: API.CustomFieldOptions = new API.CustomFieldOptions(this);
  customFields: API.CustomFields = new API.CustomFields(this);
  /**
   * Miscelaneous utility endpoints.
   *
   * Collection of utility functions that can help build integrations against this API.
   *
   */
  identity: API.Identity = new API.Identity(this);
  /**
   * Create, list and delete incident attachments.
   *
   * Incident Attachments allows you to connect resources from external systems into incidents.
   * Examples include: PagerDuty incidents and GitHub pull requests.
   *
   */
  incidentAttachments: API.IncidentAttachments = new API.IncidentAttachments(this);
  /**
   * Manage private incident memberships
   */
  incidentMemberships: API.IncidentMemberships = new API.IncidentMemberships(this);
  /**
   * View related incidents for an incident
   */
  incidentRelationships: API.IncidentRelationships = new API.IncidentRelationships(this);
  incidentRoles: API.IncidentRoles = new API.IncidentRoles(this);
  /**
   * Manage incident statuses.
   *
   * Each incident has a status, picked from one of the statuses configured in your
   * organisations settings.
   *
   * Statuses help communicate where an incident is in its lifecycle. You can use
   * statuses when filtering incidents in the dashboard, and in workflows and announcement
   * rules.
   *
   */
  incidentStatuses: API.IncidentStatuses = new API.IncidentStatuses(this);
  /**
   * View incident types.
   *
   * With incident types enabled, you can tailor your process to the situation you're
   * responding to with different custom fields and roles for each incident type.
   *
   */
  incidentTypes: API.IncidentTypes = new API.IncidentTypes(this);
  incidents: API.Incidents = new API.Incidents(this);
  /**
   * Manage the IP allowlist.
   *
   * When enabled, the IP allowlist restricts authenticated traffic from the dashboard, public API and mobile app.
   */
  ipAllowlists: API.IPAllowlists = new API.IPAllowlists(this);
  /**
   * Miscelaneous utility endpoints.
   *
   * Collection of utility functions that can help build integrations against this API.
   *
   */
  openAPIJson: API.OpenAPIJson = new API.OpenAPIJson(this);
  /**
   * Miscelaneous utility endpoints.
   *
   * Collection of utility functions that can help build integrations against this API.
   *
   */
  openAPIV3Json: API.OpenAPIV3Json = new API.OpenAPIV3Json(this);
  /**
   * Manage incident severities.
   *
   * Each incident has a severity, picked from one of the severities configured in your
   * organisations settings.
   *
   * Severities help categorise incidents, and communicate urgency/impact. You can use
   * severities when filtering incidents in the dashboard, and in workflows and announcement
   * rules.
   *
   */
  severities: API.Severities = new API.Severities(this);
  statusPages: API.StatusPages = new API.StatusPages(this);
  /**
   * View and manage alert attributes.
   *
   * Alert attributes are used to parse structured data from alerts coming in via alert sources.
   */
  alertAttributes: API.AlertAttributes = new API.AlertAttributes(this);
  /**
   * Create alerts within incident.io.
   *
   * The alerts API allows you to create alerts within incident.io by posting alert events. You
   * can use alerts to automatically trigger incidents.
   *
   * To create an alert, you must first configure an alert source in the incident.io dashboard.
   *
   */
  alertEvents: API.AlertEvents = new API.AlertEvents(this);
  /**
   * Configure your alert routes in incident.io.
   *
   * Alert routes define how alerts from different sources are processed, grouped, and routed to the right teams and people.
   */
  alertRoutes: API.AlertRoutes = new API.AlertRoutes(this);
  /**
   * Configure your alert sources in incident.io.
   *
   * Alert sources are the systems that send alerts to incident.io, which can then be routed to the right people and teams.
   */
  alertSources: API.AlertSources = new API.AlertSources(this);
  /**
   * Read your alerts in incident.io.
   *
   * Alerts are events ingested from third parties by alert sources. They can trigger incidents and escalations, as configured in alert routes.
   * To view your alerts, you can list all alerts, or show a single alert.
   * If you'd like to view only alerts that are currently firing, you can filter by status.
   * To view the alert that was created for an event in your external system, filter by deduplication key.
   *
   * If you'd like to view alerts connected to a particular incident, you can list incident alerts. You can filter by incident_id to find all alerts attached to a particular incident, or by alert_id to find the incident that a particular alert triggered.
   *
   */
  alerts: API.Alerts = new API.Alerts(this);
  catalogEntries: API.CatalogEntries = new API.CatalogEntries(this);
  catalogResources: API.CatalogResources = new API.CatalogResources(this);
  /**
   * Manage and browse catalog resources.
   *
   * Use the incident.io catalog to track services, teams, product features and anything
   * else that helps build a map of your organisation. These different categories of thing
   * become catalog types, and each instance (like a particular service or team) is a
   * catalog entry.
   *
   * Each type is made up of a series of attributes, and each attribute has a type. Types
   * can even have attributes that refer to other catalog types.
   *
   * We automatically create catalog types when you connect an integration, such as GitHub
   * repositories or PagerDuty services and teams. You can use this API to create custom
   * types, that are specifically tailored to your organisation.
   *
   * Examples might be a 'Service' type with an 'Alert channel' which you can point at a
   * Slack channel, or 'Team' which specifies its 'Manager' and 'Technical Lead' as Slack
   * users. You can then use these types to create powerful new workflows.
   *
   * Consider using our official [catalog importer](https://github.com/incident-io/catalog-importer).
   * It can be used to sync catalog data from sources like local files or GitHub and push
   * them into the incident.io catalog without having to directly interact with our public API.
   *
   */
  catalogTypes: API.CatalogTypes = new API.CatalogTypes(this);
  /**
   * Create and manage escalation paths, and create, list and filter escalations.
   *
   * With incident.io On-call you can create escalation paths that describe how a page should
   * be escalated to people and schedules.
   *
   */
  escalationPaths: API.EscalationPaths = new API.EscalationPaths(this);
  /**
   * Create and manage escalation paths, and create, list and filter escalations.
   *
   * With incident.io On-call you can create escalation paths that describe how a page should
   * be escalated to people and schedules.
   *
   */
  escalations: API.Escalations = new API.Escalations(this);
  /**
   * Manage incident follow-ups.
   *
   * Incidents can have follow-ups associated with them, which track work that should be done
   * after an incident (e.g. improving some documentation, or upgrading a dependency). They can
   * also be exported to external issue trackers.
   *
   * You can manage follow-ups in the incident Slack channel with <code>/incident follow-ups</code>, or on
   * the incident homepage.
   *
   */
  followUps: API.FollowUps = new API.FollowUps(this);
  /**
   * Read your alerts in incident.io.
   *
   * Alerts are events ingested from third parties by alert sources. They can trigger incidents and escalations, as configured in alert routes.
   * To view your alerts, you can list all alerts, or show a single alert.
   * If you'd like to view only alerts that are currently firing, you can filter by status.
   * To view the alert that was created for an event in your external system, filter by deduplication key.
   *
   * If you'd like to view alerts connected to a particular incident, you can list incident alerts. You can filter by incident_id to find all alerts attached to a particular incident, or by alert_id to find the incident that a particular alert triggered.
   *
   */
  incidentAlerts: API.IncidentAlerts = new API.IncidentAlerts(this);
  /**
   * View incident timestamps.
   *
   * Each incident has a number of timestamps; some being defaults that we set on
   * each incident for you, and other being configured for your organisation within
   * settings.
   *
   * Timestamps help to communicate when a given action was taken for a specific
   * incident, for example when it was reported, closed or fixed.
   *
   */
  incidentTimestamps: API.IncidentTimestamps = new API.IncidentTimestamps(this);
  /**
   * List incident updates.
   *
   * Incident Updates allows you to see all the updates that have been shared against a
   * particular incident. This will include any time that the Severity or Status of
   * an incident changed, alongside any additional updates that were provided.
   *
   */
  incidentUpdates: API.IncidentUpdates = new API.IncidentUpdates(this);
  /**
   * View and manage schedules.
   * Manage your full schedule of on-call rotations, including the users and rotation configuration.
   *
   */
  scheduleEntries: API.ScheduleEntries = new API.ScheduleEntries(this);
  /**
   * View and manage schedules.
   * Manage your full schedule of on-call rotations, including the users and rotation configuration.
   *
   */
  scheduleOverrides: API.ScheduleOverrides = new API.ScheduleOverrides(this);
  /**
   * View and manage schedules.
   * Manage your full schedule of on-call rotations, including the users and rotation configuration.
   *
   */
  schedules: API.Schedules = new API.Schedules(this);
  /**
   * View users.
   *
   * Users all have a single base role, and can be assigned multiple custom roles. They can be managed via your Slack workspace or SAML provider.
   *
   */
  users: API.Users = new API.Users(this);
  /**
   * Manage workflows.
   *
   * Workflows allow you to automate certain actions and behaviors based on specific triggers.
   */
  workflows: API.Workflows = new API.Workflows(this);
}

IncidentIo6.Actions = Actions;
IncidentIo6.CustomFieldOptions = CustomFieldOptions;
IncidentIo6.CustomFields = CustomFields;
IncidentIo6.Identity = Identity;
IncidentIo6.IncidentAttachments = IncidentAttachments;
IncidentIo6.IncidentMemberships = IncidentMemberships;
IncidentIo6.IncidentRelationships = IncidentRelationships;
IncidentIo6.IncidentRoles = IncidentRoles;
IncidentIo6.IncidentStatuses = IncidentStatuses;
IncidentIo6.IncidentTypes = IncidentTypes;
IncidentIo6.Incidents = Incidents;
IncidentIo6.IPAllowlists = IPAllowlists;
IncidentIo6.OpenAPIJson = OpenAPIJson;
IncidentIo6.OpenAPIV3Json = OpenAPIV3Json;
IncidentIo6.Severities = Severities;
IncidentIo6.StatusPages = StatusPages;
IncidentIo6.AlertAttributes = AlertAttributes;
IncidentIo6.AlertEvents = AlertEvents;
IncidentIo6.AlertRoutes = AlertRoutes;
IncidentIo6.AlertSources = AlertSources;
IncidentIo6.Alerts = Alerts;
IncidentIo6.CatalogEntries = CatalogEntries;
IncidentIo6.CatalogResources = CatalogResources;
IncidentIo6.CatalogTypes = CatalogTypes;
IncidentIo6.EscalationPaths = EscalationPaths;
IncidentIo6.Escalations = Escalations;
IncidentIo6.FollowUps = FollowUps;
IncidentIo6.IncidentAlerts = IncidentAlerts;
IncidentIo6.IncidentTimestamps = IncidentTimestamps;
IncidentIo6.IncidentUpdates = IncidentUpdates;
IncidentIo6.ScheduleEntries = ScheduleEntries;
IncidentIo6.ScheduleOverrides = ScheduleOverrides;
IncidentIo6.Schedules = Schedules;
IncidentIo6.Users = Users;
IncidentIo6.Workflows = Workflows;

export declare namespace IncidentIo6 {
  export type RequestOptions = Opts.RequestOptions;

  export {
    Actions as Actions,
    type ActionV1 as ActionV1,
    type ActionV2 as ActionV2,
    type ActorV2 as ActorV2,
    type AlertActorV2 as AlertActorV2,
    type UserV1 as UserV1,
    type UserV2 as UserV2,
    type WorkflowActorV2 as WorkflowActorV2,
    type ActionRetrieveResponse as ActionRetrieveResponse,
    type ActionListResponse as ActionListResponse,
    type ActionListV2Response as ActionListV2Response,
    type ActionRetrieveV2Response as ActionRetrieveV2Response,
    type ActionListParams as ActionListParams,
    type ActionListV2Params as ActionListV2Params,
  };

  export {
    CustomFieldOptions as CustomFieldOptions,
    type CustomFieldOptionV1 as CustomFieldOptionV1,
    type PaginationMeta as PaginationMeta,
    type CustomFieldOptionCreateResponse as CustomFieldOptionCreateResponse,
    type CustomFieldOptionRetrieveResponse as CustomFieldOptionRetrieveResponse,
    type CustomFieldOptionUpdateResponse as CustomFieldOptionUpdateResponse,
    type CustomFieldOptionListResponse as CustomFieldOptionListResponse,
    type CustomFieldOptionCreateParams as CustomFieldOptionCreateParams,
    type CustomFieldOptionUpdateParams as CustomFieldOptionUpdateParams,
    type CustomFieldOptionListParams as CustomFieldOptionListParams,
  };

  export {
    CustomFields as CustomFields,
    type CustomFieldFilterByOptionsV2 as CustomFieldFilterByOptionsV2,
    type CustomFieldV1 as CustomFieldV1,
    type CustomFieldV2 as CustomFieldV2,
    type CustomFieldCreateV1Response as CustomFieldCreateV1Response,
    type CustomFieldCreateV2Response as CustomFieldCreateV2Response,
    type CustomFieldListV1Response as CustomFieldListV1Response,
    type CustomFieldListV2Response as CustomFieldListV2Response,
    type CustomFieldRetrieveV1Response as CustomFieldRetrieveV1Response,
    type CustomFieldRetrieveV2Response as CustomFieldRetrieveV2Response,
    type CustomFieldUpdateV1Response as CustomFieldUpdateV1Response,
    type CustomFieldUpdateV2Response as CustomFieldUpdateV2Response,
    type CustomFieldCreateV1Params as CustomFieldCreateV1Params,
    type CustomFieldCreateV2Params as CustomFieldCreateV2Params,
    type CustomFieldUpdateV1Params as CustomFieldUpdateV1Params,
    type CustomFieldUpdateV2Params as CustomFieldUpdateV2Params,
  };

  export { Identity as Identity, type IdentityRetrieveResponse as IdentityRetrieveResponse };

  export {
    IncidentAttachments as IncidentAttachments,
    type IncidentAttachment as IncidentAttachment,
    type IncidentAttachmentCreateResponse as IncidentAttachmentCreateResponse,
    type IncidentAttachmentListResponse as IncidentAttachmentListResponse,
    type IncidentAttachmentCreateParams as IncidentAttachmentCreateParams,
    type IncidentAttachmentListParams as IncidentAttachmentListParams,
  };

  export {
    IncidentMemberships as IncidentMemberships,
    type IncidentMembershipCreateResponse as IncidentMembershipCreateResponse,
    type IncidentMembershipCreateParams as IncidentMembershipCreateParams,
  };

  export {
    IncidentRelationships as IncidentRelationships,
    type IncidentRelationshipListResponse as IncidentRelationshipListResponse,
    type IncidentRelationshipListParams as IncidentRelationshipListParams,
  };

  export {
    IncidentRoles as IncidentRoles,
    type IncidentRoleV1 as IncidentRoleV1,
    type IncidentRoleV2 as IncidentRoleV2,
    type IncidentRoleCreateResponse as IncidentRoleCreateResponse,
    type IncidentRoleRetrieveResponse as IncidentRoleRetrieveResponse,
    type IncidentRoleUpdateResponse as IncidentRoleUpdateResponse,
    type IncidentRoleListResponse as IncidentRoleListResponse,
    type IncidentRoleCreateV2Response as IncidentRoleCreateV2Response,
    type IncidentRoleListV2Response as IncidentRoleListV2Response,
    type IncidentRoleRetrieveV2Response as IncidentRoleRetrieveV2Response,
    type IncidentRoleUpdateV2Response as IncidentRoleUpdateV2Response,
    type IncidentRoleCreateParams as IncidentRoleCreateParams,
    type IncidentRoleUpdateParams as IncidentRoleUpdateParams,
    type IncidentRoleCreateV2Params as IncidentRoleCreateV2Params,
    type IncidentRoleUpdateV2Params as IncidentRoleUpdateV2Params,
  };

  export {
    IncidentStatuses as IncidentStatuses,
    type IncidentStatusV1 as IncidentStatusV1,
    type IncidentStatusCreateResponse as IncidentStatusCreateResponse,
    type IncidentStatusRetrieveResponse as IncidentStatusRetrieveResponse,
    type IncidentStatusUpdateResponse as IncidentStatusUpdateResponse,
    type IncidentStatusListResponse as IncidentStatusListResponse,
    type IncidentStatusCreateParams as IncidentStatusCreateParams,
    type IncidentStatusUpdateParams as IncidentStatusUpdateParams,
  };

  export {
    IncidentTypes as IncidentTypes,
    type IncidentType as IncidentType,
    type IncidentTypeRetrieveResponse as IncidentTypeRetrieveResponse,
    type IncidentTypeListResponse as IncidentTypeListResponse,
  };

  export {
    Incidents as Incidents,
    type CustomFieldEntryPayload as CustomFieldEntryPayload,
    type CustomFieldOptionV2 as CustomFieldOptionV2,
    type IncidentRoleAssignmentPayload as IncidentRoleAssignmentPayload,
    type IncidentStatusV2 as IncidentStatusV2,
    type IncidentTimestampValuePayload as IncidentTimestampValuePayload,
    type IncidentV1 as IncidentV1,
    type IncidentV2 as IncidentV2,
    type PaginationMetaResultWithTotal as PaginationMetaResultWithTotal,
    type Severity as Severity,
    type IncidentCreateResponse as IncidentCreateResponse,
    type IncidentRetrieveResponse as IncidentRetrieveResponse,
    type IncidentListResponse as IncidentListResponse,
    type IncidentCreateV2Response as IncidentCreateV2Response,
    type IncidentListV2Response as IncidentListV2Response,
    type IncidentRetrieveV2Response as IncidentRetrieveV2Response,
    type IncidentCreateParams as IncidentCreateParams,
    type IncidentListParams as IncidentListParams,
    type IncidentCreateV2Params as IncidentCreateV2Params,
    type IncidentListV2Params as IncidentListV2Params,
  };

  export {
    IPAllowlists as IPAllowlists,
    type IPAllowlist as IPAllowlist,
    type IPAllowlistItem as IPAllowlistItem,
    type IPAllowlistRetrieveResponse as IPAllowlistRetrieveResponse,
    type IPAllowlistUpdateResponse as IPAllowlistUpdateResponse,
    type IPAllowlistUpdateParams as IPAllowlistUpdateParams,
  };

  export { OpenAPIJson as OpenAPIJson, type OpenAPIJsonRetrieveResponse as OpenAPIJsonRetrieveResponse };

  export {
    OpenAPIV3Json as OpenAPIV3Json,
    type OpenAPIV3JsonRetrieveResponse as OpenAPIV3JsonRetrieveResponse,
  };

  export {
    Severities as Severities,
    type SeverityV1 as SeverityV1,
    type SeverityCreateResponse as SeverityCreateResponse,
    type SeverityRetrieveResponse as SeverityRetrieveResponse,
    type SeverityUpdateResponse as SeverityUpdateResponse,
    type SeverityListResponse as SeverityListResponse,
    type SeverityCreateParams as SeverityCreateParams,
    type SeverityUpdateParams as SeverityUpdateParams,
  };

  export { StatusPages as StatusPages };

  export {
    AlertAttributes as AlertAttributes,
    type AlertAttributeV2 as AlertAttributeV2,
    type AlertAttributeCreateResponse as AlertAttributeCreateResponse,
    type AlertAttributeRetrieveResponse as AlertAttributeRetrieveResponse,
    type AlertAttributeUpdateResponse as AlertAttributeUpdateResponse,
    type AlertAttributeListResponse as AlertAttributeListResponse,
    type AlertAttributeCreateParams as AlertAttributeCreateParams,
    type AlertAttributeUpdateParams as AlertAttributeUpdateParams,
  };

  export {
    AlertEvents as AlertEvents,
    type AlertEventCreateHTTPResponse as AlertEventCreateHTTPResponse,
    type AlertEventCreateHTTPParams as AlertEventCreateHTTPParams,
  };

  export {
    AlertRoutes as AlertRoutes,
    type AlertRoute as AlertRoute,
    type AlertSourcePayload as AlertSourcePayload,
    type AutoGeneratedTemplateBinding as AutoGeneratedTemplateBinding,
    type AutoGeneratedTemplateBindingPayload as AutoGeneratedTemplateBindingPayload,
    type ChannelConfigPayload as ChannelConfigPayload,
    type ChannelTarget as ChannelTarget,
    type ChannelTargetPayload as ChannelTargetPayload,
    type ConditionGroup as ConditionGroup,
    type ConditionGroupPayload as ConditionGroupPayload,
    type EscalationConfigPayload as EscalationConfigPayload,
    type Expression as Expression,
    type ExpressionPayload as ExpressionPayload,
    type GroupingKey as GroupingKey,
    type IncidentConfigPayload as IncidentConfigPayload,
    type IncidentTemplatePayload as IncidentTemplatePayload,
    type PaginationMetaResult as PaginationMetaResult,
    type ReturnsMeta as ReturnsMeta,
    type TemplateBinding as TemplateBinding,
    type TemplateBindingPayload as TemplateBindingPayload,
    type AlertRouteCreateResponse as AlertRouteCreateResponse,
    type AlertRouteRetrieveResponse as AlertRouteRetrieveResponse,
    type AlertRouteUpdateResponse as AlertRouteUpdateResponse,
    type AlertRouteListResponse as AlertRouteListResponse,
    type AlertRouteCreateParams as AlertRouteCreateParams,
    type AlertRouteUpdateParams as AlertRouteUpdateParams,
    type AlertRouteListParams as AlertRouteListParams,
  };

  export {
    AlertSources as AlertSources,
    type AlertSource as AlertSource,
    type HTTPCustomOptions as HTTPCustomOptions,
    type JiraOptions as JiraOptions,
    type ParamBindingValue as ParamBindingValue,
    type ParamBindingValuePayload as ParamBindingValuePayload,
    type TemplatePayload as TemplatePayload,
    type AlertSourceCreateResponse as AlertSourceCreateResponse,
    type AlertSourceRetrieveResponse as AlertSourceRetrieveResponse,
    type AlertSourceUpdateResponse as AlertSourceUpdateResponse,
    type AlertSourceListResponse as AlertSourceListResponse,
    type AlertSourceCreateParams as AlertSourceCreateParams,
    type AlertSourceUpdateParams as AlertSourceUpdateParams,
  };

  export {
    Alerts as Alerts,
    type AlertAttributeValueV2 as AlertAttributeValueV2,
    type AlertV2 as AlertV2,
    type AlertRetrieveResponse as AlertRetrieveResponse,
    type AlertListResponse as AlertListResponse,
    type AlertListParams as AlertListParams,
  };

  export {
    CatalogEntries as CatalogEntries,
    type CatalogEntryV2 as CatalogEntryV2,
    type CatalogEntryV3 as CatalogEntryV3,
    type CatalogTypeV2 as CatalogTypeV2,
    type CatalogTypeV3 as CatalogTypeV3,
    type CatalogEntryCreateEntryV2Response as CatalogEntryCreateEntryV2Response,
    type CatalogEntryCreateEntryV3Response as CatalogEntryCreateEntryV3Response,
    type CatalogEntryListEntriesV2Response as CatalogEntryListEntriesV2Response,
    type CatalogEntryListEntriesV3Response as CatalogEntryListEntriesV3Response,
    type CatalogEntryShowEntryV2Response as CatalogEntryShowEntryV2Response,
    type CatalogEntryShowEntryV3Response as CatalogEntryShowEntryV3Response,
    type CatalogEntryUpdateEntryV2Response as CatalogEntryUpdateEntryV2Response,
    type CatalogEntryUpdateEntryV3Response as CatalogEntryUpdateEntryV3Response,
    type CatalogEntryCreateEntryV2Params as CatalogEntryCreateEntryV2Params,
    type CatalogEntryCreateEntryV3Params as CatalogEntryCreateEntryV3Params,
    type CatalogEntryListEntriesV2Params as CatalogEntryListEntriesV2Params,
    type CatalogEntryListEntriesV3Params as CatalogEntryListEntriesV3Params,
    type CatalogEntryUpdateEntryV2Params as CatalogEntryUpdateEntryV2Params,
    type CatalogEntryUpdateEntryV3Params as CatalogEntryUpdateEntryV3Params,
  };

  export {
    CatalogResources as CatalogResources,
    type CatalogResourceListV2Response as CatalogResourceListV2Response,
    type CatalogResourceListV3Response as CatalogResourceListV3Response,
  };

  export {
    CatalogTypes as CatalogTypes,
    type CatalogTypeCreateResponse as CatalogTypeCreateResponse,
    type CatalogTypeRetrieveResponse as CatalogTypeRetrieveResponse,
    type CatalogTypeUpdateResponse as CatalogTypeUpdateResponse,
    type CatalogTypeListResponse as CatalogTypeListResponse,
    type CatalogTypeCreateParams as CatalogTypeCreateParams,
    type CatalogTypeUpdateParams as CatalogTypeUpdateParams,
  };

  export {
    EscalationPaths as EscalationPaths,
    type EscalationPath as EscalationPath,
    type EscalationPathNode as EscalationPathNode,
    type EscalationPathNodeIfElse as EscalationPathNodeIfElse,
    type EscalationPathNodeIfElsePayload as EscalationPathNodeIfElsePayload,
    type EscalationPathNodePayload as EscalationPathNodePayload,
    type WeekdayIntervalConfig as WeekdayIntervalConfig,
    type EscalationPathCreateResponse as EscalationPathCreateResponse,
    type EscalationPathRetrieveResponse as EscalationPathRetrieveResponse,
    type EscalationPathUpdateResponse as EscalationPathUpdateResponse,
    type EscalationPathCreateParams as EscalationPathCreateParams,
    type EscalationPathUpdateParams as EscalationPathUpdateParams,
  };

  export {
    Escalations as Escalations,
    type EscalationV2 as EscalationV2,
    type EscalationCreateResponse as EscalationCreateResponse,
    type EscalationRetrieveResponse as EscalationRetrieveResponse,
    type EscalationListResponse as EscalationListResponse,
    type EscalationCreateParams as EscalationCreateParams,
    type EscalationListParams as EscalationListParams,
  };

  export {
    FollowUps as FollowUps,
    type ExternalIssueReference as ExternalIssueReference,
    type FollowUp as FollowUp,
    type FollowUpRetrieveResponse as FollowUpRetrieveResponse,
    type FollowUpListResponse as FollowUpListResponse,
    type FollowUpListParams as FollowUpListParams,
  };

  export {
    IncidentAlerts as IncidentAlerts,
    type AlertSlim as AlertSlim,
    type IncidentSlim as IncidentSlim,
    type IncidentAlertListResponse as IncidentAlertListResponse,
    type IncidentAlertListParams as IncidentAlertListParams,
  };

  export {
    IncidentTimestamps as IncidentTimestamps,
    type IncidentTimestamp as IncidentTimestamp,
    type IncidentTimestampRetrieveResponse as IncidentTimestampRetrieveResponse,
    type IncidentTimestampListResponse as IncidentTimestampListResponse,
  };

  export {
    IncidentUpdates as IncidentUpdates,
    type IncidentUpdateListResponse as IncidentUpdateListResponse,
    type IncidentUpdateListParams as IncidentUpdateListParams,
  };

  export {
    ScheduleEntries as ScheduleEntries,
    type ScheduleEntry as ScheduleEntry,
    type ScheduleEntryListResponse as ScheduleEntryListResponse,
    type ScheduleEntryListParams as ScheduleEntryListParams,
  };

  export {
    ScheduleOverrides as ScheduleOverrides,
    type UserReferencePayloadV2 as UserReferencePayloadV2,
    type ScheduleOverrideCreateResponse as ScheduleOverrideCreateResponse,
    type ScheduleOverrideCreateParams as ScheduleOverrideCreateParams,
  };

  export {
    Schedules as Schedules,
    type Schedule as Schedule,
    type ScheduleHolidaysPublicConfigPayload as ScheduleHolidaysPublicConfigPayload,
    type ScheduleRotationHandover as ScheduleRotationHandover,
    type ScheduleRotationWorkingInterval as ScheduleRotationWorkingInterval,
    type ScheduleCreateResponse as ScheduleCreateResponse,
    type ScheduleRetrieveResponse as ScheduleRetrieveResponse,
    type ScheduleUpdateResponse as ScheduleUpdateResponse,
    type ScheduleListResponse as ScheduleListResponse,
    type ScheduleCreateParams as ScheduleCreateParams,
    type ScheduleUpdateParams as ScheduleUpdateParams,
    type ScheduleListParams as ScheduleListParams,
  };

  export {
    Users as Users,
    type RbacRole as RbacRole,
    type UserWithRoles as UserWithRoles,
    type UserRetrieveResponse as UserRetrieveResponse,
    type UserListResponse as UserListResponse,
    type UserListParams as UserListParams,
  };

  export {
    Workflows as Workflows,
    type EngineParamBinding as EngineParamBinding,
    type EngineParamBindingPayload as EngineParamBindingPayload,
    type EngineReference as EngineReference,
    type ManagementMeta as ManagementMeta,
    type StepConfigPayload as StepConfigPayload,
    type TriggerSlim as TriggerSlim,
    type Workflow as Workflow,
    type WorkflowDelay as WorkflowDelay,
    type WorkflowCreateResponse as WorkflowCreateResponse,
    type WorkflowRetrieveResponse as WorkflowRetrieveResponse,
    type WorkflowUpdateResponse as WorkflowUpdateResponse,
    type WorkflowListResponse as WorkflowListResponse,
    type WorkflowCreateParams as WorkflowCreateParams,
    type WorkflowRetrieveParams as WorkflowRetrieveParams,
    type WorkflowUpdateParams as WorkflowUpdateParams,
  };
}
